# Generated by Django 2.2.5 on 2019-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=10)),
                ('id_producto', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='')),
                ('valor', models.IntegerField()),
                ('plataforma', models.CharField(max_length=10)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
