# Generated by Django 2.2.5 on 2019-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('cedula', models.IntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
